#!/bin/bash
## Description: Check for Drupal coding-standards violations using phpcs (run `ddev install` first)
## Usage: coding-standards
## Example: "ddev coding-standards"

/var/www/html/vendor/bin/phpcs -p $DDEV_DOCROOT/modules/contrib/$PROJECT_NAME
