#!/bin/bash
## Description: Execute any unit tests for the project (run `ddev install` first)
## Usage: unit-tests
## Example: "ddev unit-tests"

/var/www/html/vendor/bin/phpunit -c /var/www/html/$DDEV_DOCROOT/core/phpunit.xml.dist --verbose --group=$PROJECT_NAME /var/www/html/$DDEV_DOCROOT/modules/contrib/$PROJECT_NAME
